fun main() {
    var MoscowMTS = OperatorRussia()
    MoscowMTS.SetOperator()
    MoscowMTS.SetCity()
    MoscowMTS.SetPriceInternet()
    MoscowMTS.SetP()
    println()
    MoscowMTS.GetOperator()
    MoscowMTS.GetCity()
    MoscowMTS.GetPriceInternet()
    MoscowMTS.GetQ()
    println()
    var Telecom = TVconnection()
    Telecom.SetInfo()
    Telecom.SetPriceInternet()
    println()
    Telecom.GetInfo()
    Telecom.GetPriceInternet()
}